my_profile:
  target: dev_snowflake
  outputs:
    dev_snowflake:
      type: snowflake
      user: ""
      password: ""
      account: ""
      database: "WALMART_DB"
      schema: "SILVER"
      warehouse: "COMPUTE_WH"
      role: "ACCOUNTADMIN"
      threads: 4
  
