--Set theole warehouse database and schema

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE WALMART_DB;

USE SCHEMA WALMART_DB.RAW;


--Create a storage integration with S3 bucket and iam role previously created in AWS

CREATE STORAGE INTEGRATION IF NOT EXISTS WM_STORES_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::************:role/wm-e2e-snowflake-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://walmart-end-to-end-project/wm-stores/')

DESC INTEGRATION WM_STORES_INT;

CREATE FILE FORMAT IF NOT EXISTS WM_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
DATE_FORMAT = 'AUTO'
NULL_IF = ('NA', ''); 


-- --Create an external S3 stage table to hold data for transfer into snowflake

CREATE STAGE IF NOT EXISTS WM_STORES_S3_STAGE
STORAGE_INTEGRATION = WM_STORES_INT
URL = 's3://walmart-end-to-end-project/wm-stores/'
FILE_FORMAT = WM_CSV_FORMAT;


LIST @WALMART_DB.RAW.WM_STORES_S3_STAGE;

CREATE TABLE IF NOT EXISTS STORES
(
Store INT,
Type VARCHAR(1),
Size INT,
Loaded_At TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


--create snowpipe to automatically ingest
CREATE OR REPLACE PIPE WALMART_DB.RAW.STAGING_TO_RAW_STORES
AUTO_INGEST = TRUE
AS 
COPY INTO WALMART_DB.RAW.STORES (
    Store,
    Type,
    Size,
    Loaded_At 
)
FROM (
    SELECT
        $1::INT,
        $2::VARCHAR(1),
        $3::INT,
        CURRENT_TIMESTAMP()
    FROM @WALMART_DB.RAW.WM_STORES_S3_STAGE
)
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.RAW.WM_CSV_FORMAT);


SHOW PIPES;

-- ALTER PIPE WALMART_DB.RAW.STAGING_TO_RAW_STORES REFRESH;
    
DROP TABLE WALMART_DB.SILVER.FACT_SNAPSHOT;

WALMART_DB.SILVER
SELECT * FROM WALMART_DB.GOLD.WALMART_DATE_DIM;

SELECT * FROM WALMART_DB.GOLD.WALMART_store_DIM;

SELECT * FROM WALMART_DB.GOLD.WALMART_FACT_TABLE;
